import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import React from 'react';
import { ImageBackground, Pressable, StyleSheet, Text, View } from 'react-native';
import { useColors } from '@/hooks/useColors';

export type Reel = { id: string; image: number; eyebrow: string; title: string; creator: string; duration: string; tags: string[]; hypeScore: number; signal: string };
type ReelCardProps = { reel: Reel; height: number; watchPercent: number; liked: boolean; rewatched: number; isCurrent: boolean; signalCaptured: boolean; onLike: () => void; onSkip: () => void; onRewatch: () => void; onWhy: () => void };

export function ReelCard({ reel, height, watchPercent, liked, rewatched, isCurrent, signalCaptured, onLike, onSkip, onRewatch, onWhy }: ReelCardProps) {
  const colors = useColors();
  const progressWidth = `${watchPercent}%` as `${number}%`;
  return <View style={[styles.page, { minHeight: height }]}>
    <ImageBackground source={reel.image} style={styles.visual} imageStyle={styles.visualImage}>
      <LinearGradient colors={['rgba(7,16,30,0.12)', 'rgba(7,16,30,0.22)', 'rgba(7,16,30,0.96)']} locations={[0, 0.45, 1]} style={StyleSheet.absoluteFill} />
      <View style={styles.visualTop}><View style={styles.eyebrowPill}><View style={[styles.liveDot, { backgroundColor: colors.coral }]} /><Text style={[styles.eyebrowText, { color: colors.white }]}>{reel.eyebrow.toUpperCase()}</Text></View><Text style={[styles.duration, { color: colors.white }]}>{reel.duration}</Text></View>
      <View style={styles.visualCopy}><Text style={[styles.visualTitle, { color: colors.white }]}>{reel.title}</Text><Text style={[styles.creator, { color: colors.white }]}>{reel.creator}</Text></View>
      <View style={styles.hypeBadge}><Ionicons name="shield-checkmark" size={14} color={colors.lime} /><Text style={[styles.hypeText, { color: colors.white }]}>HypeShield {reel.hypeScore}%</Text></View>
    </ImageBackground>
    <View style={[styles.detailPanel, { backgroundColor: colors.surface }]}>
      <View style={styles.metaRow}><View style={styles.tagRow}>{reel.tags.map((tag) => <View key={tag} style={[styles.tag, { backgroundColor: colors.surfaceSoft }]}><Text style={[styles.tagText, { color: colors.secondaryForeground }]}>{tag}</Text></View>)}</View><Text style={[styles.percent, { color: colors.cyan }]}>{watchPercent}% watched</Text></View>
      <View style={[styles.progressTrack, { backgroundColor: colors.surfaceElevated }]}><View style={[styles.progressFill, { width: progressWidth, backgroundColor: colors.cyan }]} /></View>
      <View style={styles.actionRow}><ActionButton icon={liked ? 'heart' : 'heart-outline'} label={liked ? 'Liked' : 'Like'} active={liked} onPress={onLike} /><ActionButton icon="repeat" label={rewatched > 0 ? ('Replay x' + rewatched) : 'Rewatch'} active={rewatched > 0} onPress={onRewatch} /><ActionButton icon="close-circle-outline" label="Skip" onPress={onSkip} /><Pressable accessibilityRole="button" testID={'why-' + reel.id} onPress={onWhy} style={({ pressed }) => [styles.whyButton, { backgroundColor: colors.cyan, opacity: pressed ? 0.82 : 1 }]}><Ionicons name="sparkles" size={16} color={colors.black} /><Text style={[styles.whyText, { color: colors.black }]}>Why this?</Text></Pressable></View>
      {isCurrent && signalCaptured ? <View style={[styles.signalNotice, { borderColor: colors.border, backgroundColor: colors.card }]}><View style={[styles.signalIcon, { backgroundColor: colors.surfaceSoft }]}><Ionicons name="git-branch-outline" size={16} color={colors.violet} /></View><View style={styles.signalCopy}><Text style={[styles.signalLabel, { color: colors.mutedForeground }]}>SIGNAL CAPTURED</Text><Text style={[styles.signalText, { color: colors.foreground }]}>{reel.signal} · context beats keywords.</Text></View><Ionicons name="chevron-forward" size={16} color={colors.mutedForeground} /></View> : <Text style={[styles.nextHint, { color: colors.mutedForeground }]}>Keep scrolling to teach Reelwise what feels useful.</Text>}
    </View>
  </View>;
}
function ActionButton({ icon, label, active, onPress }: { icon: keyof typeof Ionicons.glyphMap; label: string; active?: boolean; onPress: () => void }) { const colors = useColors(); return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.actionButton, { opacity: pressed ? 0.64 : 1 }]}><Ionicons name={icon} size={20} color={active ? colors.coral : colors.foreground} /><Text style={[styles.actionLabel, { color: colors.mutedForeground }]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({
  page: { paddingHorizontal: 16, paddingBottom: 18 }, visual: { height: 360, overflow: 'hidden', justifyContent: 'space-between', padding: 18 }, visualImage: { borderRadius: 28 }, visualTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, eyebrowPill: { flexDirection: 'row', alignItems: 'center', gap: 7, backgroundColor: 'rgba(7,16,30,0.62)', paddingHorizontal: 10, paddingVertical: 7, borderRadius: 99 }, liveDot: { width: 7, height: 7, borderRadius: 99 }, eyebrowText: { fontSize: 10, fontWeight: '700', letterSpacing: 1.1 }, duration: { fontSize: 12, fontWeight: '600', backgroundColor: 'rgba(7,16,30,0.62)', paddingHorizontal: 9, paddingVertical: 7, borderRadius: 99 }, visualCopy: { gap: 7, paddingBottom: 44, maxWidth: '86%' }, visualTitle: { fontSize: 28, lineHeight: 33, fontWeight: '700', letterSpacing: -0.6 }, creator: { fontSize: 13, opacity: 0.82 }, hypeBadge: { position: 'absolute', left: 18, bottom: 18, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(7,16,30,0.72)', paddingHorizontal: 10, paddingVertical: 7, borderRadius: 99 }, hypeText: { fontSize: 11, fontWeight: '600' }, detailPanel: { borderBottomLeftRadius: 28, borderBottomRightRadius: 28, padding: 16, gap: 14 }, metaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 }, tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, flex: 1 }, tag: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8 }, tagText: { fontSize: 10, fontWeight: '600' }, percent: { fontSize: 11, fontWeight: '700' }, progressTrack: { height: 4, borderRadius: 99, overflow: 'hidden' }, progressFill: { height: 4, borderRadius: 99 }, actionRow: { flexDirection: 'row', alignItems: 'center', gap: 13 }, actionButton: { alignItems: 'center', gap: 5 }, actionLabel: { fontSize: 9, fontWeight: '600' }, whyButton: { marginLeft: 'auto', flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 14 }, whyText: { fontSize: 11, fontWeight: '800' }, signalNotice: { borderWidth: 1, borderRadius: 17, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 10 }, signalIcon: { width: 30, height: 30, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, signalCopy: { flex: 1, gap: 2 }, signalLabel: { fontSize: 9, letterSpacing: 1.1, fontWeight: '700' }, signalText: { fontSize: 11, lineHeight: 16, fontWeight: '600' }, nextHint: { fontSize: 11, lineHeight: 16 },
});
