import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import React from 'react';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
type Props = { visible: boolean; onClose: () => void };
const watched = ['Java Meme', 'Software Engineer Lifestyle', 'Coding Interview', 'Laptop Comparison'];
const inferred = ['Programming', 'Developer Career', 'Technology'];
export function WhyThisSheet({ visible, onClose }: Props) { const colors = useColors(); return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={[styles.backdrop, { backgroundColor: colors.scrim }]}><Pressable style={StyleSheet.absoluteFill} onPress={onClose} /><View style={[styles.sheet, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.grabber} /><View style={styles.sheetHeader}><View><Text style={[styles.kicker, { color: colors.coral }]}>WHY THIS?</Text><Text style={[styles.title, { color: colors.foreground }]}>The recommendation trail</Text></View><Pressable accessibilityRole="button" onPress={onClose} style={styles.close}><Ionicons name="close" size={21} color={colors.mutedForeground} /></Pressable></View><Section title="WHAT YOU WATCHED" items={watched} color={colors.violet} /><Section title="WHAT WE INFERRED" items={inferred} color={colors.cyan} /><LinearGradient colors={[colors.surfaceSoft, colors.surface]} style={styles.latent}><Text style={[styles.label, { color: colors.mutedForeground }]}>LATENT INTEREST</Text><Text style={[styles.latentText, { color: colors.cyan }]}>Software Engineering</Text><Text style={[styles.latentCopy, { color: colors.secondaryForeground }]}>Java is a context signal, not the primary destination.</Text></LinearGradient><View style={styles.reason}><View style={[styles.reasonIcon, { backgroundColor: colors.coral }]}><Ionicons name="sparkles" size={14} color={colors.black} /></View><View style={styles.reasonCopy}><Text style={[styles.label, { color: colors.mutedForeground }]}>WHY THIS RECOMMENDATION</Text><Text style={[styles.reasonText, { color: colors.foreground }]}>System design is a related skill that expands the inferred interest.</Text></View></View><View style={[styles.filterNote, { borderColor: colors.border }]}><Ionicons name="shield-checkmark" size={16} color={colors.lime} /><Text style={[styles.filterText, { color: colors.secondaryForeground }]}>HypeShield selected educational depth over repeat-topic clickbait.</Text></View></View></View></Modal>; }
function Section({ title, items, color }: { title: string; items: string[]; color: string }) { const colors = useColors(); return <View style={styles.section}><Text style={[styles.label, { color: colors.mutedForeground }]}>{title}</Text><View style={styles.itemList}>{items.map((item) => <View key={item} style={styles.item}><View style={[styles.itemDot, { backgroundColor: color }]} /><Text style={[styles.itemText, { color: colors.secondaryForeground }]}>{item}</Text><Ionicons name="checkmark" size={14} color={color} /></View>)}</View></View>; }
const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end' }, sheet: { borderTopLeftRadius: 28, borderTopRightRadius: 28, borderWidth: 1, paddingHorizontal: 18, paddingTop: 9, paddingBottom: 30, gap: 16 }, grabber: { alignSelf: 'center', width: 40, height: 4, borderRadius: 99, backgroundColor: '#5D7193', marginBottom: 4 }, sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, kicker: { fontSize: 10, fontWeight: '800', letterSpacing: 1.2, marginBottom: 4 }, title: { fontSize: 22, lineHeight: 27, fontWeight: '800', letterSpacing: -0.5 }, close: { padding: 4 }, section: { gap: 8 }, label: { fontSize: 9, fontWeight: '800', letterSpacing: 1.1 }, itemList: { gap: 7 }, item: { flexDirection: 'row', alignItems: 'center', gap: 9 }, itemDot: { width: 6, height: 6, borderRadius: 99 }, itemText: { flex: 1, fontSize: 13, fontWeight: '600' }, latent: { borderRadius: 17, padding: 13, gap: 5 }, latentText: { fontSize: 20, lineHeight: 24, fontWeight: '800' }, latentCopy: { fontSize: 11, lineHeight: 16 }, reason: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 }, reasonIcon: { width: 28, height: 28, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, reasonCopy: { flex: 1, gap: 5 }, reasonText: { fontSize: 13, lineHeight: 18, fontWeight: '700' }, filterNote: { borderWidth: 1, borderRadius: 13, padding: 10, flexDirection: 'row', gap: 8, alignItems: 'center' }, filterText: { fontSize: 10, lineHeight: 15, flex: 1 } });
