import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { LinearGradient } from 'expo-linear-gradient';
import React, { useEffect, useRef, useState } from 'react';
import { Dimensions, FlatList, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { Reel, ReelCard } from '@/components/ReelCard';
import { useInteractions } from '@/context/InteractionContext';
const { height: WINDOW_HEIGHT } = Dimensions.get('window');
const REEL_PAGE_HEIGHT = Math.max(665, WINDOW_HEIGHT - 126);
const CANDIDATE_REELS: Reel[] = [
  { id: 'java', image: require('@/assets/images/reel-code.jpg'), eyebrow: 'Current reel', title: 'When Java asks for one more abstraction', creator: '@buildinpublic', duration: '0:18', tags: ['Java', 'meme'], hypeScore: 92, signal: 'coding humor' },
  { id: 'lifestyle', image: require('@/assets/images/reel-lifestyle.jpg'), eyebrow: 'Signal two', title: 'A day in the life: tabs > tasks', creator: '@shipshape', duration: '0:31', tags: ['Lifestyle', 'builder'], hypeScore: 88, signal: 'engineer lifestyle' },
  { id: 'interview', image: require('@/assets/images/reel-code.jpg'), eyebrow: 'Signal three', title: 'Big-O when you meet the interviewer', creator: '@complexityclub', duration: '0:22', tags: ['Interviews', 'humor'], hypeScore: 94, signal: 'problem solving' },
  { id: 'laptop', image: require('@/assets/images/reel-lifestyle.jpg'), eyebrow: 'Signal four', title: 'The laptop you buy vs. the laptop you need', creator: '@stackedframes', duration: '0:27', tags: ['Laptops', 'tech'], hypeScore: 86, signal: 'technology context' },
  { id: 'clickbait', image: require('@/assets/images/reel-api.jpg'), eyebrow: 'Filtered candidate', title: 'This one trick will make you a 10x engineer', creator: '@hustleloop', duration: '0:14', tags: ['Hype', 'clickbait'], hypeScore: 41, signal: 'empty promise' },
];
const REELS = CANDIDATE_REELS.filter((reel) => reel.hypeScore >= 80);
export default function FeedScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const listRef = useRef<FlatList<Reel>>(null); const [activeIndex, setActiveIndex] = useState(0); const [expandedWhy, setExpandedWhy] = useState(false); const { liked, rewatched, watchPercent, demoMode, likeReel, skipReel, rewatchReel, advanceWatch, toggleDemoMode, resetDemo } = useInteractions(); const topInset = Platform.OS === 'web' ? 67 : insets.top; const bottomInset = Platform.OS === 'web' ? 34 : insets.bottom;
  useEffect(() => { const timer = setInterval(() => advanceWatch(REELS[activeIndex].id), 1250); return () => clearInterval(timer); }, [activeIndex, advanceWatch]);
  const currentReel = REELS[activeIndex];
  const feedback = async (action: () => void) => { await Haptics.selectionAsync(); action(); }; const goNext = (index: number) => { const nextIndex = Math.min(REELS.length - 1, index + 1); listRef.current?.scrollToIndex({ index: nextIndex, animated: true }); };
  return <View style={[styles.root, { backgroundColor: colors.background }]}><LinearGradient colors={[colors.background, colors.surface, colors.background]} style={StyleSheet.absoluteFill} />
    <View style={[styles.header, { paddingTop: topInset + 10 }]}><View><Text style={[styles.wordmark, { color: colors.foreground }]}>reelwise<Text style={{ color: colors.coral }}>.</Text></Text><Text style={[styles.headerSub, { color: colors.mutedForeground }]}>your tech taste, decoded</Text></View><View style={styles.headerActions}><Pressable accessibilityRole="button" testID="demo-toggle" onPress={() => feedback(toggleDemoMode)} style={({ pressed }) => [styles.demoPill, { borderColor: demoMode ? colors.cyan : colors.border, backgroundColor: demoMode ? colors.surfaceSoft : colors.card, opacity: pressed ? 0.75 : 1 }]}><View style={[styles.demoDot, { backgroundColor: demoMode ? colors.cyan : colors.mutedForeground }]} /><Text style={[styles.demoText, { color: demoMode ? colors.cyan : colors.mutedForeground }]}>{demoMode ? 'DEMO LIVE' : 'DEMO'}</Text></Pressable><Pressable accessibilityRole="button" testID="reset-demo" onPress={() => feedback(resetDemo)} style={({ pressed }) => [styles.iconButton, { backgroundColor: colors.surfaceSoft, opacity: pressed ? 0.7 : 1 }]}><Ionicons name="refresh" size={16} color={colors.secondaryForeground} /></Pressable></View></View>
    <FlatList ref={listRef} data={REELS} keyExtractor={(item) => item.id} renderItem={({ item, index }) => <ReelCard reel={item} height={REEL_PAGE_HEIGHT} watchPercent={watchPercent[item.id] ?? 0} liked={liked.includes(item.id)} rewatched={rewatched[item.id] ?? 0} isCurrent={index === 0} onLike={() => feedback(() => likeReel(item.id))} onSkip={() => feedback(() => { skipReel(item.id); goNext(index); })} onRewatch={() => feedback(() => rewatchReel(item.id))} onWhy={() => { setExpandedWhy(true); feedback(() => undefined); }} />} onViewableItemsChanged={({ viewableItems }) => { const next = viewableItems[0]?.index; if (typeof next === 'number') setActiveIndex(next); }} viewabilityConfig={{ itemVisiblePercentThreshold: 60 }} snapToInterval={REEL_PAGE_HEIGHT} decelerationRate="fast" showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingTop: topInset + 72, paddingBottom: bottomInset + 116 }} getItemLayout={(_, index) => ({ length: REEL_PAGE_HEIGHT, offset: REEL_PAGE_HEIGHT * index, index })} />
    <View pointerEvents="box-none" style={[styles.bottomOverlay, { bottom: bottomInset + 78 }]}><View style={[styles.counterPill, { backgroundColor: colors.scrim }]}><Text style={[styles.counterText, { color: colors.white }]}>{activeIndex + 1} / {REELS.length}</Text><View style={[styles.counterLine, { backgroundColor: colors.surfaceSoft }]}><View style={[styles.counterFill, { backgroundColor: colors.coral, width: (`${((activeIndex + 1) / REELS.length) * 100}%` as `${number}%`) }]} /></View></View></View>
    {expandedWhy && <View style={[styles.explanationLayer, { paddingTop: topInset + 12 }]}><Pressable style={StyleSheet.absoluteFill} onPress={() => setExpandedWhy(false)} /><View style={[styles.explanationCard, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.explanationHeader}><View><Text style={[styles.explanationKicker, { color: colors.coral }]}>WHY THIS?</Text><Text style={[styles.explanationTitle, { color: colors.foreground }]}>Reelwise followed the thread.</Text></View><Pressable accessibilityRole="button" onPress={() => setExpandedWhy(false)}><Ionicons name="close" size={21} color={colors.mutedForeground} /></Pressable></View><View style={styles.field}><Text style={[styles.fieldLabel, { color: colors.mutedForeground }]}>CURRENT REEL</Text><Text style={[styles.fieldValue, { color: colors.foreground }]}>{currentReel.title}</Text></View><View style={styles.field}><Text style={[styles.fieldLabel, { color: colors.mutedForeground }]}>INTEREST DETECTED</Text><View style={styles.interestRow}><Text style={[styles.interestValue, { color: colors.cyan }]}>Software Engineering / Technology</Text><Text style={[styles.confidence, { color: colors.lime }]}>91%</Text></View></View><View style={styles.field}><Text style={[styles.fieldLabel, { color: colors.mutedForeground }]}>WHY</Text><Text style={[styles.reason, { color: colors.secondaryForeground }]}>You lingered on developer-life context across four different topics. Java is the vehicle — engineering practice is the destination.</Text></View><LinearGradient colors={[colors.surfaceSoft, colors.surface]} style={styles.recommendation}><View style={styles.recHeading}><View style={[styles.recIcon, { backgroundColor: colors.coral }]}><Ionicons name="play" size={13} color={colors.black} /></View><View><Text style={[styles.fieldLabel, { color: colors.coral }]}>RECOMMENDED TECH REEL</Text><Text style={[styles.recTitle, { color: colors.foreground }]}>How modern software engineers design scalable APIs</Text></View></View><View style={styles.recGrid}><InfoCell label="CATEGORY" value="Systems · APIs" /><InfoCell label="DIFFICULTY" value="Intermediate" /><InfoCell label="CONFIDENCE" value="91%" accent={colors.lime} /></View><Text style={[styles.recWhy, { color: colors.secondaryForeground }]}>WHY THIS RECOMMENDATION <Text style={{ color: colors.mutedForeground }}>Adjacent depth without repeating the same topic.</Text></Text></LinearGradient><View style={styles.hypeRow}><Ionicons name="shield-checkmark" size={16} color={colors.lime} /><Text style={[styles.hypeCopy, { color: colors.secondaryForeground }]}><Text style={{ fontWeight: '800', color: colors.lime }}>HypeShield passed</Text> · practical signal, named tradeoffs, no empty promise.</Text></View></View></View>}
  </View>;
}
function InfoCell({ label, value, accent }: { label: string; value: string; accent?: string }) { const colors = useColors(); return <View style={styles.infoCell}><Text style={[styles.fieldLabel, { color: colors.mutedForeground }]}>{label}</Text><Text style={[styles.infoValue, { color: accent ?? colors.foreground }]}>{value}</Text></View>; }
const styles = StyleSheet.create({ root: { flex: 1 }, header: { position: 'absolute', zIndex: 5, left: 16, right: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, wordmark: { fontSize: 24, lineHeight: 27, fontWeight: '700', letterSpacing: -1.2 }, headerSub: { fontSize: 10, letterSpacing: 0.3, marginTop: 2 }, headerActions: { flexDirection: 'row', gap: 8, alignItems: 'center' }, demoPill: { flexDirection: 'row', gap: 7, alignItems: 'center', paddingHorizontal: 10, paddingVertical: 8, borderRadius: 99, borderWidth: 1 }, demoDot: { width: 6, height: 6, borderRadius: 99 }, demoText: { fontSize: 9, fontWeight: '800', letterSpacing: 0.8 }, iconButton: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center', borderRadius: 12 }, bottomOverlay: { position: 'absolute', left: 16, right: 16, alignItems: 'flex-end' }, counterPill: { flexDirection: 'row', alignItems: 'center', gap: 9, borderRadius: 99, paddingHorizontal: 10, paddingVertical: 7 }, counterText: { fontSize: 10, fontWeight: '700' }, counterLine: { width: 44, height: 3, borderRadius: 99, overflow: 'hidden' }, counterFill: { height: 3, borderRadius: 99 }, explanationLayer: { ...StyleSheet.absoluteFillObject, zIndex: 20, paddingHorizontal: 12, backgroundColor: 'rgba(7,16,30,0.55)' }, explanationCard: { borderRadius: 27, borderWidth: 1, padding: 18, gap: 15, shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 22, elevation: 8 }, explanationHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, explanationKicker: { fontSize: 10, fontWeight: '800', letterSpacing: 1.2, marginBottom: 4 }, explanationTitle: { fontSize: 21, lineHeight: 26, fontWeight: '700', letterSpacing: -0.5 }, field: { gap: 5 }, fieldLabel: { fontSize: 9, letterSpacing: 1, fontWeight: '800' }, fieldValue: { fontSize: 13, lineHeight: 18, fontWeight: '600' }, interestRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, interestValue: { fontSize: 17, lineHeight: 21, fontWeight: '700', letterSpacing: -0.2 }, confidence: { fontSize: 12, fontWeight: '800' }, reason: { fontSize: 12, lineHeight: 18 }, recommendation: { borderRadius: 20, padding: 14, gap: 13 }, recHeading: { flexDirection: 'row', gap: 10, alignItems: 'flex-start' }, recIcon: { width: 28, height: 28, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, recTitle: { fontSize: 14, lineHeight: 19, fontWeight: '700', marginTop: 4, maxWidth: 260 }, recGrid: { flexDirection: 'row', gap: 18 }, infoCell: { gap: 4 }, infoValue: { fontSize: 11, fontWeight: '700' }, recWhy: { fontSize: 10, lineHeight: 15, fontWeight: '800' }, hypeRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 7 }, hypeCopy: { fontSize: 10, lineHeight: 15, flex: 1 } });
